name: Documentation
on: 
  push:
    branches:
      - main
  pull_request:

jobs: 
  production-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: repo

      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.2"

      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Pull LDoc
        uses: actions/checkout@v2
        with:
          repository: impulsh/LDoc
          path: ldoc

      - name: Build LDoc
        working-directory: ldoc
        run: luarocks make

      - name: Build docs
        working-directory: repo
        run: ldoc . --fatalwarnings

      - name: Copy assets
        working-directory: repo
        run: |
          cp -v docs/css/* docs/html
          cp -v docs/js/* docs/html
          
      - name: Deploy in production
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: MULTIVERSE-Project/documentation
          publish_branch: production
          publish_dir: repo/docs/html
          destination_dir: ./${{ github.event.repository.name }}